// learn2code/react_vue_angular/vuejs/00-with-yarn-vue-create-ts/src/views/Home.vue
<template>
	<div class="home">
		<img alt="Vue logo" src="../assets/vuelogo.png" />
		<h1>
			{{ title }}
		</h1>

		<p>
			Hot singles in your area. <br />
			Hotter vue in your
			<a href="https://vuejs.org" target="_blank" rel="noopener noreferrer"
				>documentation</a
			>.
		</p>
	</div>
</template>

<script lang="ts">
export default {
	data() {
		return {
			title: 'Brekeke Vue'
		}
	}
}
</script>

<style lang="scss" scoped>
img {
	width: 45%;
}
h1 {
	margin-top: 0;
}
</style>

// learn2code/react/03-with-yarn-cra-ts-template/src/views/Home.tsx
import React from 'react'
import './Home.scss'
import logo from '../assets/logo.svg'

const Home: React.FC = () => {
	return (
		<div className="home">
			<img className="logo" src={logo} alt="react logo" />

			<h1>Title</h1>

			<p>
				Hot singles in your area. <br />
				Hotter react in your&nbsp;
				<a
					href="https://reactjs.org/docs"
					target="_blank"
					rel="noopener noreferrer"
				>
					documentation
				</a>
				.
			</p>
		</div>
	)
}

export default Home
