// learn2code/react_vue_angular/vuejs/00-with-yarn-vue-create-3-ts/src/views/Tunes.vue
<template>
	<div>
		<h1>Tunes</h1>
		<tunes-search-form />
		<tunes-list />
	</div>
</template>

<script lang="ts">
import TunesSearchForm from '@/components/tunes/TunesSearchForm.vue'
import TunesList from '@/components/tunes/TunesList.vue'

export default {
	components: {
		TunesSearchForm,
		TunesList
	}
}
</script>

<style lang="scss" scoped></style>

// learn2code/react/03-with-yarn-cra-ts-template/src/views/Tunes.tsx
import React, { useState } from 'react'
import TunesList from '../components/tunes/TunesList'
import TunesSearchForm from '../components/tunes/TunesSearchForm'

const Tunes: React.FC = () => {
	const [title, setTitle] = useState('Tunes')

	const handleSearchFormSubmit = (data: string) => {
		setTitle(data)
	}
	return (
		<article className="tunes">
			<h1>{title}</h1>
			<TunesSearchForm onSearchFormSubmit={handleSearchFormSubmit} />
			<TunesList />
		</article>
	)
}

export default Tunes
