// learn2code/react/03-with-yarn-cra-ts-template/src/App.tsx
import React from 'react'
import './App.scss'
import { Switch, Route } from 'react-router-dom'
import TheNavigation from './components/TheNavigation'
import Home from './views/Home'
import About from './views/About'
import Tunes from './views/Tunes'

function App() {
	return (
		<div className="App">
			<header>
				<TheNavigation />
			</header>
			<main className="content">
				<Switch>
					<Route path="/" component={Home} exact />
					<Route path="/tunes" component={Tunes} />
					<Route path="/about" component={About} />
				</Switch>
			</main>
		</div>
	)
}

export default App

// learn2code/react_vue_angular/vuejs/00-with-yarn-vue-create-ts/src/App.vue
<template>
	<div id="app">
		<header>
			<the-navigation />
		</header>
		<main class="content">
			<router-view />
		</main>
	</div>
</template>

<script>
import TheNavigation from '@/components/TheNavigation.vue'

export default {
	components: {
		TheNavigation
	}
}
</script>

<style src="@/assets/scss/main.scss" lang="scss"></style>
